export default {
    login: "Đăng Nhập",
    register: "Đăng Ký",
    showPassword: "Hiển thị mật khẩu",
    shop: "Cửa Hàng",
    about: "Thông Tin",
    contact: "Liên Hệ",
    admin: "Trang Quản Trị",
    profile: "Thông Tin",
    setting: "Cài Đặt",
    logout: "Đăng Xuất",
    success: "Thành Công",
    error: "Thất Bại",
    login_success: "Đăng Nhập Thành Công",
    login_error: "Không đúng",
    product: {
        overview: "TỔNG QUAN SẢN PHẨM",
        all: "Tất cả sản phẩm",
        relative: "Sản phẩm tương tự",
        detail: {
            description: "Mô tả",
            information: "Thông tin thêm",
            review: "Đánh giá",
            add_cart: "THÊM VÀO GIỎ HÀNG",
            categories: "Danh Mục",
            original_price: "Giá Gốc",
            price_sale: "Giá Giảm",
        },
    },
    side_bar: {
        help: "Trợ giúp",
        user: "Quản Lý Người Dùng",
        product: "Quản Lý Sản Phẩm",
        menu: "Quản Lý Danh Mục",
        slide: "Quản Lý Slide",
        customer: "Quản Lý Khách Hàng",
        multipleFile: "Tải File",
        link: "Tìm kiếm bằng url",
    },
    comment: {
        display: "Bình Luận",
        reply: "Trả Lời",
        add_comment: "Thêm Bình Luận",
    },
    contact_page: {
        form: "Biểu Mẫu",
        description: "Viết những thông tin cần thiết",
        send: "Gửi Yêu Cầu",
        information: "Thông Tin Liên Hệ",
        address: "Địa Chỉ",
        business: "Yêu Cầu Kinh Doanh",
        employment: {
            title: "Tìm Việc",
            content:
                "Chúng tôi luôn tìm kiếm những người tài năng để tham gia vào đội ngũ của chúng tôi.",
        },
    },
    user_management: {
        title: "Danh Sách Người Dùng",
        no: "STT",
        name: "Tên",
        email: "Email",
        phone: "Số Điện Thoại",
        created: "Ngày Tạo",
        export_excel: "Xuất Excel",
        export_success: "Xuất Thành Công",
        cancel: "Hủy",
        add_user: {
            title: "Thêm Người Dùng",
            name: "Tên",
            email: "Email",
            phone: "Số Điện Thoại",
            password: "Mật Khẩu",
            avatar: "Ảnh Đại Diện",
            attachments: "Tài Liệu Đính Kèm",
            success: "Tạo Thành Công",
        },
        edit_user: {
            title: "Chỉnh sửa người dùng",
            name: "Tên",
            email: "Email",
            phone: "Số Điện Thoại",
            password: "Mật Khẩu",
            avatar: "Ảnh Đại Diên",
            attachments: "Tài Liệu Đính Kèm",
            success: "Chỉnh Sửa Thành Công",
        },
        confirm: {
            title: "Thông Báo",
            content: "Bạn đang thay đổi nguời dùng. Bạn chắc chắn với điều đó?",
            cancel: "Hủy",
            confirm: "OK",
        },
        delete: {
            title: "Thông Báo",
            content:
                "Bạn đang thực hiện quá trình xóa người dùng. Bạn chắc chắn về điều đó?",
            cancel: "Hủy",
            confirm: "OK",
            success: "Xóa Thành Công",
        },
    },
    profile: {
        title: "Hồ Sơ Người Dùng",
        setting: "Cài Đặt",
        prefer_language: {
            title: "Ngôn Ngữ Mong Muốn",
            content:
                "Tùy chọn này sẽ thay đổi ngôn ngữ được sử dụng cho giao diện người dùng của ứng dụng. Điều này sẽ không ảnh hưởng đến bất kỳ nội dung nào do người dùng tạo.",
        },
        activity: {
            title: "Hoạt Động",
            followers: "Người Theo Dõi",
            following: "Người Đang Theo Dõi",
            friends: "Bạn Bè",
            follow: "Theo Dõi",
            about: "Thông Tin Bản Thân",
        },
        profile: {
            title: "Hồ Sơ",
            name: "Tên",
            email: "Email",
            password: "Mật Khẩu",
            phone: "Số Điện Thoại",
            department: "Công Việc",
            birthday: "Sinh Nhật",
            address: "Địa Chỉ",
            gender: {
                title: "Giới Tính",
                male: "Nam",
                female: "Nữ",
            },
            upload: "Ảnh",
            album: "Album",
            save: "Lưu",
        },
    },
    dark_mode: {
        title: "Chế Độ Tối",
        content:
            "Tùy chọn này sẽ thay đổi giao diện được sử dụng cho giao diện người dùng của ứng dụng. Điều này sẽ không ảnh hưởng đến bất kỳ nội dung nào do người dùng tạo.",
    },
    cart: {
        title: "Giỏ",
        total_price: "Tổng",
        tax: "Thuế",
        total_tax: "Tổng Sau Thuế",
        payment: "Thanh Toán",
        delete_all: "Xóa Tất Cả",
    },
    cart_page: {
        image: "Ảnh",
        name: "Tên",
        price: "Giá",
        qty: "Số Lượng",
        total: "Tổng",
        delete: "Xóa",
        coupon: "Mã Giảm Giá",
        update: "Cập Nhật Giỏ Hàng",
        cart_total: "Tổng Giỏ Hàng",
        tax: "Thuế",
        total_tax: "Tổng Sau Thuế",
        customer: "Thông Tin Khách Hàng",
        payment: "Thanh Toán",
    },
    file: {
        name: "Danh sách file Upload",
    },
};